# Generated by Django 4.2.10 on 2024-02-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description2',
            field=models.TextField(default=1, max_length=500, verbose_name='Описание2'),
            preserve_default=False,
        ),
    ]
