# Generated by Django 4.2.10 on 2024-02-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_blog_description3_blog_description4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description7',
            field=models.TextField(default=1, max_length=500, verbose_name='Описание7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='title5',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='title6',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='description6',
            field=models.TextField(max_length=500, verbose_name='Описание6'),
        ),
    ]
