# Generated by Django 4.2.10 on 2024-02-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_setting_image2_remove_setting_image3_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='Settings',
        ),
    ]
