# Generated by Django 4.2.10 on 2024-02-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_setting_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='description2',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='title3',
            field=models.CharField(default=1, max_length=255, verbose_name='Загловок2'),
            preserve_default=False,
        ),
    ]
