# Generated by Django 4.2.10 on 2024-02-26 08:37

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_settings_description2_settings_title3'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='image2',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/'),
            preserve_default=False,
        ),
    ]
