# Generated by Django 4.2.10 on 2024-02-26 08:50

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_settings_image3_settings_image4_settings_image5'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='description3',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='description4',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='description5',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='description6',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='image6',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='image7',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='image8',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='image9',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='title4',
            field=models.CharField(default=1, max_length=255, verbose_name='Загловок2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='title5',
            field=models.CharField(default=1, max_length=255, verbose_name='Загловок2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='title6',
            field=models.CharField(default=1, max_length=255, verbose_name='Загловок2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='title7',
            field=models.CharField(default=1, max_length=255, verbose_name='Загловок2'),
            preserve_default=False,
        ),
    ]
